#include <unity.h>
#include <ALHIDJoystick.hpp>
#include <HID-Project.h>


void hid_check_copied_constants_match()
{
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_CENTERED,     GAMEPAD_DPAD_CENTERED);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_UP,           GAMEPAD_DPAD_UP);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_UP_RIGHT,     GAMEPAD_DPAD_UP_RIGHT);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_RIGHT,        GAMEPAD_DPAD_RIGHT);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_DOWN_RIGHT,   GAMEPAD_DPAD_DOWN_RIGHT);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_DOWN,         GAMEPAD_DPAD_DOWN);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_DOWN_LEFT,    GAMEPAD_DPAD_DOWN_LEFT);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_LEFT,         GAMEPAD_DPAD_LEFT);
    TEST_ASSERT_EQUAL(AL_GAMEPAD_DPAD_UP_LEFT,      GAMEPAD_DPAD_UP_LEFT);
}

void runHidTests()
{
    RUN_TEST(hid_check_copied_constants_match);
}